avatar: /images/avatar.jpg # 网站 Logo
background: # 既是博客的背景，又是文章默认头图
    path: /images/background_mainpage.jpg
    width: 1280
    height: 720
favicon:
  href: /favicon.ico # 网站图标
  type: image/x-icon # 图标类型，可能的值有(image/png, image/vnd.microsoft.icon, image/x-icon, image/gif)

function: # 功能开关，可选值（true,false）
  globalToc: true # 开启该功能会自动开启文章 TOC（文章目录） 功能
  wordCount: true # 是否开启文章字数统计 (true, false)
  copyCode: true # 是否允许复制代码块

imageCDN: # 图片 CDN 功能
  enable: false # 开启该功能  
  origin: /../../images/ # 图片原始目录
  to: https://cdn.jsdelivr.net/gh/nexmoe/nexmoe.github.io@latest/images/ # 图片 CDN 域名

# 自定义样式，启用后可在站点的source文件夹下新建custom.css自定义站点样式
customStyles:
  - custom.css
  
# 附加图标库 使用说明：https://docs.nexmoe.com/config/icon
#iconlib: # //at.alicdn.com/t/font_1038733_0xvrvpg9c0r.css

menu:
    回到首页:
        - /
        - icon-home
    文章归档:
        - /archive.html
        - icon-container
    我的朋友:
        - /PY.html
    给我赞助:
        - /images/money.png
        - icon-coffee
    关于博主:
        - https://i.nexmoe.com/
        - icon-info-circle

widgets:
    - name: search
      enable: true
      options: 
        search: 
            type: engine # 可选engine（用搜索引擎搜索）、swiftype、或local（本地搜索）
            url: https://cn.bing.com/search?q=site:nexmoe.com # 搜索引擎地址，在type为swiftype时无效 e.g:https://www.google.com/search?q={你的博客链接}
            id: <swiftype-id> # swiftype的id，见启用教程。在type为engine时无效
    - name: social
      enable: true
      options: 
        social:
            QQ群:
                - https://jq.qq.com/?_wv=1027&k=5CfKHun
                - icon-QQ
                - rgb(249, 174, 8)
                - rgba(249, 174, 8, .1)
            哔哩哔哩:
                - https://space.bilibili.com/178188049
                - icon-bilibili
                - rgb(231, 106, 141)
                - rgba(231, 106, 141, .1)
            GitHub:
                - https://github.com/Kyunana097/
                - icon-github
                - rgb(25, 23, 23)
                - rgba(25, 23, 23, .1)
    - name: category
      enable: true
    - name: tagcloud
      enable: true
      options: 
        maxTagcloud: 17  # 标签云组件显示的标签数量，0 表示不限制
    - name: hitokoto # 一言 widget
      enable: false
      options: 
        widgetHitokoto: # 一言组件
            loading_placeholder: '🚀 获取中...' # 正在一言时的占位符
            loading_error_placeholder: '🐞 获取失败...' # 加载一言失败时的占位符
            category: # 一言句子类型（可选），不配置的话随机获取，详见 https://developer.hitokoto.cn/sentence/#%E5%8F%A5%E5%AD%90%E7%B1%BB%E5%9E%8B-%E5%8F%82%E6%95%B0
    - name: archive #settings: widgetAchive
      enable: true
      options:
        widgetAchive: #文章归档组件
            archive_type: 'year' #按月展示还是按年展示
            show_count: true  #是否展示数量
    - name: recent_posts
      enable: true
    - name: link #settings: widgetLink
      enable: false
      options: 
        widgetLink: #链接组件
            - title: 折影轻梦
              img: https://cdn.jsdelivr.net/gh/nexmoe/nexmoe.github.io@latest/images/avatar.png
              link : https://nexmoe.com/
